language: java
jdk:
  - openjdk 17

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIAQMGPSQ62GXIOZ2OT
    secret_access_key: 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
    bucket: leehyunwoo-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIAQMGPSQ62GXIOZ2OT
    secret_access_key: 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
    bucket: leehyunwoo-springboot-build
    key: webservice.zip
    bundle_type: zip
    application: leehyunwoo-springboot-webservice
    deployment_group: leehyunwoo-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - kaway0418@naver.com